tasks:
- init: make build

  command: |
    echo 'make serve &'
    echo "$(gp url 4000)/main/parser"

# ports:
# - port: 4000
#   visibility: public
#   # onOpen: open-preview
# - port: 31337
#   visibility: public

github:
  prebuilds:
    main: true
    gitpod: true
    branches: true
